<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AlgoBuild>true</AlgoBuild>
    <AlgoPublish>false</AlgoPublish>
    <IncludeSource>true</IncludeSource>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.21" />
  </ItemGroup>

</Project>