<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AlgoBuild>true</AlgoBuild>
    <AlgoPublish>false</AlgoPublish>
    <IncludeSource>true</IncludeSource>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.*-*" />
  </ItemGroup>
</Project>